---
title: "R Notebook"
output: html_notebook
---

CASE STUDY


Load data waste collection, round 1

```{r}
setwd("C:/Users/LiaDenisse/Documents/OR and DS/TSP")
# in this tables, node 1 is the depot and node 368 is the dumpsite
waste_nodes <- read.csv("data/waste_nodes_2.csv")  
#waste_nodes$node <- waste_nodes$id + 1
waste_nodes$demand <- waste_nodes$q
waste_nodes$demand[368] <- 0
waste_nodes$time[1] <-0
waste_nodes$time[368] <- 25*60
names(waste_nodes) <- c("id","x_coord","y_coord", "bearing", "q", "time","node","demand")
waste_edges <- read.csv("data/waste_edges_2.csv")

library(Matrix)
row <- (waste_edges$from2)
column <- (waste_edges$to2)
dis <- waste_edges$distance
time <- waste_edges$time

matrix_dist <- sparseMatrix(row,column,x=dis)
matrix_time <- sparseMatrix(row,column,x=time)
matrix_time <-unname(as.matrix(matrix_time))

M <- matrix( nrow = 368, ncol = 368)
for( i in 1:368){
  for(j in 1:368){
    M[i,j] <- distance_inf(matrix_dist,i,j)
  }
}

M[1,368] <- 1000 #we don't want to go from the depot to the dumpsite directly
dumpsite <- 368


collection_time <- waste_nodes$time
Q <- 800
demand <- waste_nodes$demand

#edges <- waste_edges[(!waste_edges$from %in% c(366,367)) | (!waste_edges$to %in% c(366,367)), ]

```


Load data waste collection, round 2

```{r}
setwd("C:/Users/LiaDenisse/Documents/OR and DS/TSP/leia_round2/")
waste_edges_df <- read.csv("waste_edges2.csv")
# in this tables, node 1 is the depot and node 368 is the dumpsite
waste_nodes <- read.csv("waste_nodes2.csv")  
#waste_nodes$node <- waste_nodes$id + 1
waste_nodes$demand <- waste_nodes$q
waste_nodes$demand[1304] <- 0
waste_nodes$time[1] <-0
waste_nodes$time[1304] <- 25*60
names(waste_nodes) <- c("id","x_coord","y_coord", "bearing", "q", "time","node","demand")
waste_edges <- read.csv("waste_edges3.csv")

 M <- unname(as.matrix(waste_edges))
M1 <- M
M1[1304,1]<-0
dumpsite <- 1304


#library(Matrix)
#row <- (waste_edges_df$from2)
#column <- (waste_edges_df$to2)
#time <- waste_edges_df$time

matrix_time <- read.csv("waste_edges_time.csv")
matrix_time <-unname(as.matrix(matrix_time))

collection_time <- waste_nodes$time
Q <- 800
demand <- waste_nodes$demand

```

CASE STUDY 1: waste collection

```{r}

#################### route first ########################

system.time(nn<- nearest_neighbor_tour_start(M,1) )
#user  system elapsed 
#0.02    0.00    0.01 
system.time(gr <- greedy_algorithm_tour(M))
#user  system elapsed 
#1.59    0.25    1.87 
system.time(ni <- nearest_insertion_tour(M))  
#user  system elapsed 
#0.82    0.06    0.96 
system.time(rnn <- repetitive_nearest_neighbor_tour(M))  
#user  system elapsed 
#2.54    0.01    2.57
fn<- furthest_neighbor_tour_start(M,1) #366007.1


plot_tour(waste_nodes,ni, labels =FALSE)

tour_length(M,nn) #34.14373   
tour_length(M,gr) #2023.573   
tour_length(M,ni) #33.98213 
tour_length(M,rnn) #34.14373


system.time(nn_2opt <- improvement_2opt(M,nn, asymmetric = TRUE)) #no improvement

#improve initial tour

system.time(nn_3opt <- ThreeOpt_R(nn,M,max_improvements = 50))
#   user  system elapsed 
# 136.94    0.37  145.69 

tour_length(M,nn_3opt) #22.89135

system.time(nn_3opt <- ThreeOpt_R_greedy(nn,M,max_improvements = 70, nodes_to_avoid = c(1,dumpsite)))
#improvements:  53 
#   user  system elapsed 
#  30.45    0.03   30.64 
system.time(gr_3opt <- ThreeOpt_R_greedy(gr,M,max_improvements = 70, nodes_to_avoid = c(1,dumpsite)))
#improvements:  47 
# user  system elapsed 
# 37.38    0.03   38.17 
system.time(ni_3opt <- ThreeOpt_R_greedy(ni,M,max_improvements = 70, nodes_to_avoid = c(1,dumpsite)))
#improvements:  70 
#   user  system elapsed 
#  30.48    0.06   30.73 

tour_length(M,nn_3opt) #22.94796
tour_length(M,gr_3opt) #21.95053
tour_length(M,ni_3opt) #21.59316

plot_tour(waste_nodes,ni_3opt, labels =FALSE) + theme_void()


#################### cluster second ########################

giant_tour <-  reorder_tour(ni_3opt,1) #starts from the depot
giant_tour <- giant_tour[-c(length(giant_tour)-1,length(giant_tour))] #quitamos end depot y dumpsite

M[1,368] <- M[368,1]
system.time(split_solution <- split_R_replenish(giant_tour,800,demand,M,dumpsite, improve=TRUE, max_imp = 10)) 
#  user  system elapsed 
#   0.53    0.00    0.55

# total length

split_solution$distance # 28.03594
tour_length(M, c(1,split_solution[[2]],368))+ tour_length(M,c(368,split_solution[[1]],368,1))  # 28.03594
 
# time?

system.time(split_solutiont <- split_R_replenish_time(giant_tour, Q, demand, M,dumpsite, collection_time, matrix_time, 8*60*60, improve = TRUE, max_imp = 10)) 

# user  system elapsed 
# 0.44    0.00    0.43 

split_solutiont$nvehicles
split_solutiont[[1]]$distance  # 28.03594
split_solutiont[[1]]$time # 5.127472 hrs

tour_length(M, c(1,split_solutiont[[1]][[2]],368))+ tour_length(M,c(368,split_solutiont[[1]][[1]],368,1)) 

#plots

plot_cvrp_tour(waste_nodes,split_solution, dumpsite = dumpsite, labels=FALSE) + theme_void()
plot_cvrp_tour(waste_nodes,split_solution, dumpsite = dumpsite, labels=FALSE, nodes_to_avoid = c(1,368), trips_to_plot = 2) + theme_void()
plot_tour(waste_nodes,ni_3opt, labels =FALSE)



####### cluster first ##########

## let's try k means, because total demand is 1359 units and max capacity 800, then at least two trips will be necessary to visit all the houses. 

dt <- waste_nodes[-c(1,368),c("x_coord", "y_coord", "demand", "node")]
km <- kmeans(dt[,c("x_coord","y_coord")], centers = 2, iter.max = 10, nstart = 1)
print(km)

cl1 <- dt[(km$cluster== 1),]
cl2 <- dt[(km$cluster== 2),]
sum(cl1$demand) # 754
sum(cl2$demand) #605

length(cl1$node)
length(cl2$node)

 cluster <- list()
 cluster[[1]] <- cl1$node
 cluster[[2]] <- cl2$node

plot_cvrp_tour(waste_nodes,cluster, dumpsite = 368, labels=FALSE, segments = FALSE)

##### tsp within each cluster
 
# cluster 1
 
st1 <- c(1,cl1$node,368)
st1<- st1[order(st1)]

M1 <- M[st1,st1]

nn1<- nearest_neighbor_tour_start(M1,1) 
nn <- st1[nn1]
tour_length(M,nn) # 9021.98

gr1<- greedy_algorithm_tour(M1) 
gr <- st1[gr1]
tour_length(M,gr) # 6013.928

ni1<- greedy_algorithm_tour(M1) 
ni <- st1[ni1]
tour_length(M,ni) # 6013.928

system.time(feasible_tour1 <- make_tour_feasible(M,st1))
tour_length(M,feasible_tour1) # 21.41877

system.time(feasible_tour1_imp <- ThreeOpt_R_start(feasible_tour1,M,max_improvements = 50))
feasible_tour1_imp <- reorder_tour(feasible_tour1_imp,1)
tour_length(M,feasible_tour1_imp) #20.03683


# cluster 2
 
st2 <- c(368,cl2$node)
st2<- st2[order(st2)]

M2 <- M[st2,st2]

nn1<- nearest_neighbor_tour_start(M2,1) 
nn <- st2[nn1]
tour_length(M,nn) # 9016.567

gr1<- greedy_algorithm_tour(M2) 
gr <- st2[gr1]
tour_length(M,gr) # 7010.175

ni1<- greedy_algorithm_tour(M2) 
ni <- st2[ni1]
tour_length(M,ni) # 7010.175

system.time(feasible_tour2 <- make_tour_feasible(M,st2))
tour_length(M,feasible_tour2) # 21.41877
length(feasible_tour2)

system.time(feasible_tour2_imp <- ThreeOpt_R_start(feasible_tour2,M,max_improvements = 50))
feasible_tour2_imp <- reorder_tour(feasible_tour2_imp,368)
tour_length(M,feasible_tour2_imp) #19.98281

###

s1 <- feasible_tour1_imp
s2 <- feasible_tour2_imp

solution <- list()
solution[[1]] <- s1[2:(length(s1)-2)]
solution[[2]] <- s2[2:(length(s2)-1)]


plot_cvrp_tour(waste_nodes,solution, dumpsite = 368, labels=FALSE)

plot_cvrp_tour(waste_nodes,solution, dumpsite = 368, labels=FALSE, nodes_to_avoid = c(1,368))



```



CASE STUDY 2: waste collection
```{r}

#################### route first ########################

system.time(nn<- nearest_neighbor_tour_start(M,1) )
# user  system elapsed 
# 0.07    0.01    0.16
system.time(gr <- greedy_algorithm_tour(M1)) #uso M1 para forzar q el depot y el dumpsite esten unidos
# user  system elapsed 
# 47.63   10.50   58.73 
system.time(ni <- nearest_insertion_tour(M1) ) 
# user  system elapsed 
# 15.91    0.42   16.40 

tour_length(M,nn)  # 75.87031
tour_length(M,gr)  # 114054.8
tour_length(M,ni)  # 106.9347

plot_tour(waste_nodes,nn, labels =FALSE)

system.time(nn_2opt <- improvement_2opt(M,nn, asymmetric = TRUE)) #no improvement

system.time(nn_3opt <- ThreeOpt_R_greedy(nn,M1,50,c(1,1304)))
#improvements:  50 
# user  system elapsed 
# 85.36    0.25   87.28 

system.time(ni_3opt <- ThreeOpt_R_greedy(ni,M1,50,c(1,1304)))
# improvements:  50 
# user  system elapsed 
# 51.11    0.03   51.64 

tour_length(M,nn_3opt)  # 63.25629
tour_length(M,ni_3opt)  # 83.2741

plot_tour(waste_nodes,nn_3opt, labels =FALSE) + theme_void()

#################### cluster second ########################

giant_tour <-  reorder_tour(nn_3opt,1) #starts from the depot
giant_tour <- giant_tour[-c(length(giant_tour)-1,length(giant_tour))] #quitamos end depot y dumpsite

system.time(split_solution <- split_R_replenish(giant_tour,800,demand,M,dumpsite, improve = TRUE, max_imp = 10)) 
#user  system elapsed   case study 2   length = 81.80538, 6 trips  - > IMPROVE: 71.55318
#0.03    0.00    0.05 
# 27.96    0.04   28.80 (IMPROVE = TRUE)

plot_cvrp_tour(waste_nodes,split_solution, dumpsite = dumpsite, labels=FALSE) + theme_dark()

# taking TIME in consideration
# without improvement
system.time(list <- split_R_replenish_time(giant_tour, Q, demand, M,dumpsite, collection_time, matrix_time, 8*60*60, improve = FALSE))

# 8 hrs shift
# user  system elapsed  # 3 vehicles, 
#  0.00    0.01    0.01

list[[1]]$distance #----41.63548
+ list[[2]]$distance #--40.77108 
+ list[[3]]$distance #-- 8.45106
# total --------------- 90.85762

list[[1]]$time #----28743 (7.984167 hrs)
+ list[[2]]$time #--28682.1 (7.96725 hrs) 
+ list[[3]]$time #-- 8.45106 (1.277333 hrs)
# total --------------- 62023.5 (17.22875 hrs)

# WITH SUBTOUR IMPROVEMENT

system.time(list_imp <- split_R_replenish_time(giant_tour, Q, demand, M,dumpsite, collection_time, matrix_time, 8*60*60, improve = TRUE, max_imp = 10))
# user  system elapsed 
#  23.40    0.00   23.58
# 8 hrs shift
# 3 vehicles
list_imp[[1]]$distance #----37.72552
+ list_imp[[2]]$distance #--35.27191 
+ list_imp[[3]]$distance #-- 7.491232
# total --------------- 80.48866

list_imp[[1]]$time #----28150.8 (7.819667 hrs)
+ list_imp[[2]]$time #--27811.7 (7.725472 hrs) 
+ list_imp[[3]]$time #-- 4403.3 (1.223139 hrs)
# total --------------- 60365.8 (16.76828 hrs)


system.time(list_imp9 <- split_R_replenish_time(giant_tour, Q, demand, M,dumpsite, collection_time, matrix_time, 9*60*60, improve = TRUE, max_imp = 10))
# user  system elapsed 
# 28.44    0.03   31.20 
# 9 hrs shift
# 2 vehicles
list_imp[[1]]$distance #----39.32952
+ list_imp[[2]]$distance #--34.45991 
# total ------------------- 73.78943

list_imp[[1]]$distance #----30219.1  (8.394194 hrs)
+ list_imp[[2]]$distance #--27721.2  (7.700333 hrs)
# total ------------------- 57940.3 (16.09453 hrs)

#######  plots

plot_tour(waste_nodes,nn_3opt, labels =FALSE)
plot_cvrp_tour(waste_nodes,split_solution, dumpsite = dumpsite, labels=FALSE) + theme_dark()

# 9 hrs shift solution
plot_cvrp_tour(waste_nodes,list_imp9[[1]], dumpsite = dumpsite, labels=FALSE)+ theme_void()
plot_cvrp_tour(waste_nodes,list_imp9[[2]], dumpsite = dumpsite, labels=FALSE)+ theme_void()


# 8 hrs shift solution
plot_cvrp_tour(waste_nodes,list_imp[[1]], dumpsite = dumpsite, labels=FALSE) + theme_void()
plot_cvrp_tour(waste_nodes,list_imp[[2]], dumpsite = dumpsite, labels=FALSE)  + theme_void()
plot_cvrp_tour(waste_nodes,list_imp[[3]], dumpsite = dumpsite, labels=FALSE)  + theme_void()


```




sweep method case study 1
```{r}



# clusters

system.time(sweep_solution <- sweep_depot_dumpsite (waste_nodes, 800, M, 1, 368))

# ajustar la solucion

must_link <- waste_edges[waste_edges$type == 0, c("from2", "to2")]

solution_adj <- adjust_clusters(must_link,sweep_solution)

get_total_demand_tour(waste_nodes,solution_adj[[1]]) # 786
get_total_demand_tour(waste_nodes,solution_adj[[2]]) # 573


plot_cvrp_tour(waste_nodes,sweep_solution, dumpsite = 368, labels=FALSE, segments = FALSE)
pl <- plot_cvrp_tour(waste_nodes,sweep_solution, dumpsite = 368, labels=FALSE, segments = FALSE) + theme_void()



# solve TSP within each cluster

#cluster 1

system.time(cl1 <- is_initial_tour_feasible(solution_adj,2, first = TRUE, M, dumpsite)) 
#   user  system elapsed 
#  2.30    0.07    2.41 
tour_length(M,cl1[[1]]) #13.03254
s1 

#cluster 2

system.time(cl2 <- is_initial_tour_feasible(solution_adj,1, first = FALSE, M, dumpsite))  
#   user  system elapsed 
#   9.18    0.33   10.08 

tour_length(M,cl2[[1]]) #18.29957


###

solution <- list()
solution[[2]] <- cl1[[1]][2:(length(cl1[[1]])-2)]
solution[[1]] <- cl2[[1]][2:(length(cl2[[1]])-1)]

tour_length(M,cl1[[1]]) + tour_length(M,cl2[[1]])  # 31.33211


plot_cvrp_tour(waste_nodes,solution, dumpsite = 368, labels=FALSE) + theme_minimal()
pl <- plot_cvrp_tour(waste_nodes,solution, dumpsite = 368, labels=FALSE) + theme_void()


pdf("C:/Users/LiaDenisse/Documents/OR and DS/TSP/imagenes/case study 1/cluster first/case_Study1_cluster.pdf")
print(pl)  
dev.off()





```



sweep method case study 2
```{r}

# sweep solution
system.time(sweep_solution <- sweep_depot_dumpsite (waste_nodes, 800, M, 1, dumpsite)) #0.43
plot_cvrp_tour(waste_nodes,sweep_solution, dumpsite, labels=FALSE, segments=FALSE) 

#pam - Partitioning Around Medoids

ncluster <- 6

dt <- waste_nodes[-c(1,dumpsite),c("x_coord", "y_coord", "demand", "node")]
library("cluster")
pam <- pam(x=dt[,c("x_coord","y_coord")], k=ncluster, keep.diss=TRUE, keep.data=TRUE)
medoids1 <- as.numeric(rownames(pam$medoids))

cluster <- list()
cluster_demand <-c()

for(i in 1:ncluster) {
  cluster[[i]] <- dt[(pam$clustering== i),]
  cluster_demand[i] <- sum(cluster[[i]]$demand) 
}

big_cluster <- cluster[[which.max(cluster_demand)]]$node
pam2 <- pam(x=dt[dt$node %in% big_cluster,c("x_coord","y_coord")], k=2, keep.diss=TRUE, keep.data=TRUE)
medoids2 <- as.numeric(rownames(pam2$medoids))

  cluster1 <- as.numeric(names(pam2$clustering[(pam2$clustering== 1)]))
  cluster2 <-  as.numeric(names(pam2$clustering[(pam2$clustering== 2)]))


cluster <- list()
cluster_demand <-c()

for(i in 1:7) {
  if(i < 2){
    cluster[[i]] <- dt[(pam$clustering== i),]$node
  cluster_demand[i] <- sum(dt[dt$node %in% cluster[[i]], "demand"]) 
  } else  if(i == 2) {
  cluster[[i]] <- cluster1
  cluster_demand[i] <-  sum(dt[dt$node %in% cluster1, "demand"])
  } else if (i == 3) {
  cluster[[i]] <- cluster2
  cluster_demand[i] <- sum(dt[dt$node %in% cluster2, "demand"])
   } else{
  cluster[[i]] <- dt[(pam$clustering== (i-1)),]$node
  cluster_demand[i] <- sum(dt[dt$node %in% cluster[[i]], "demand"]) 
  }
}
 


plot_cvrp_tour(waste_nodes,cluster, dumpsite, labels=FALSE, segments=FALSE) + theme_void() 


# ajustar la solucion

must_link <- waste_edges_df[waste_edges_df$type == 0, c("from2", "to2")]
cluster_2 <- list()
cluster_2[[1]] <- cluster[[5]]
cluster_2[[2]] <- cluster[[4]]
cluster_2[[3]] <- cluster[[6]]
cluster_2[[4]] <- cluster[[7]]
cluster_2[[5]] <- cluster[[1]]
cluster_2[[6]] <- cluster[[2]]
cluster_2[[7]] <- cluster[[3]]

solution_adj <- adjust_clusters(must_link,cluster_2)


solution_2 <- list()
solution_2[[1]] <- solution_adj[[1]]
solution_2[[2]] <- solution_adj[[2]]
solution_2[[3]] <- solution_adj[[3]]
solution_2[[4]] <- solution_adj[[4]]
solution_2[[5]] <- solution_adj[[5]]
solution_2[[6]] <- solution_adj[[6]]
solution_2[[7]] <- solution_adj[[7]]



 plot_cvrp_tour(waste_nodes,solution_adj, dumpsite, labels=FALSE, segments=FALSE, nodes_to_avoid = c(1,dumpsite))  + theme_void()



# solve TSP within each cluster

# check if considering only the nodes within each cluster, it is possible to construct a feasible tour

system.time(cl1 <- is_initial_tour_feasible(solution_2,1, first = TRUE, M, dumpsite))  #False, 247
system.time(cl2 <- is_initial_tour_feasible(solution_2,2, first = FALSE, M, dumpsite))  #False, 161
system.time(cl3 <- is_initial_tour_feasible(solution_2,3, first = FALSE, M, dumpsite)) #False, 182
system.time(cl4 <- is_initial_tour_feasible(solution_2,4, first = FALSE, M, dumpsite))  #False, 161
system.time(cl5 <- is_initial_tour_feasible(solution_2,5, first = FALSE, M, dumpsite))  #False, 168
system.time(cl6 <- is_initial_tour_feasible(solution_2,6, first = FALSE, M, dumpsite))  #False, 213
system.time(cl7 <- is_initial_tour_feasible(solution_2,7, first = FALSE, M, dumpsite))  #False, 170

tours <- list()
tours[[1]] <- cl1[[1]]
tours[[2]] <- cl2[[1]]
tours[[3]] <- cl3[[1]]
tours[[4]] <- cl4[[1]]
tours[[5]] <- cl5[[1]]
tours[[6]] <- cl6[[1]]
tours[[7]] <- cl7[[1]]
plot_cvrp_tour(waste_nodes,tours, dumpsite, labels=FALSE)+theme_void()

### check time, 9 hrs: 32,400, 8 hrs: 28,800

## 9 hours, solution:

tour_time(matrix_time,collection_time,c(1,tours[[1]][3:(length(tours[[1]])-1)],dumpsite)) + tour_time(matrix_time,collection_time,tours[[2]]) + tour_time(matrix_time,collection_time,tours[[3]])+matrix_time[dumpsite,1] #31113.8


tour_time(matrix_time,collection_time,c(1,tours[[4]][2:length(tours[[4]])])) + tour_time(M,collection_time,tours[[5]]) + tour_time(M,collection_time,tours[[6]]) + tour_time(M,collection_time,tours[[7]]) + matrix_time[dumpsite,1] #30836.33

full_tour <- c(1,tours[[1]][3:(length(tours[[1]])-1)], tours[[2]], tours[[3]][2:length(tours[[3]])],1)
tour_length(M,full_tour) #37.15541

full_tour <- c(1,tours[[4]][4:(length(tours[[4]])-1)], tours[[5]], tours[[6]][2:length(tours[[6]])],tours[[7]][2:length(tours[[7]])],1)
tour_length(M,full_tour) #37.15541

#colors
#[1] "#1B9E77" "#D95F02" "#7570B3" "#E7298A" "#66A61E" "#E6AB02" "#A6761D"

#vehicle 1
v1 <- list()
v1[[3]] <- tours[[1]][3:(length(tours[[1]])-1)]
v1[[2]] <- tours[[2]][2:(length(tours[[2]])-1)]
v1[[1]] <- tours[[3]][2:(length(tours[[3]])-1)]

plot_cvrp_tour(waste_nodes,v1, dumpsite, labels=FALSE, colors=rev(c("#1B9E77", "#D95F02","#7570B3")))+theme_void()

#vehicle 2
v2 <- list()
v2[[4]] <- c(tours[[4]][2:(length(tours[[4]])-1)])
v2[[3]] <- c(tours[[5]][2:(length(tours[[5]])-1)])
v2[[2]] <- c(tours[[6]][2:(length(tours[[6]])-1)])
v2[[1]] <- c(tours[[7]][2:(length(tours[[7]])-1)])

plot_cvrp_tour(waste_nodes,v2, dumpsite, labels=FALSE, colors = rev(c("#E7298A", "#66A61E", "#E6AB02", "#A6761D")))+theme_void()


## 8 hours solution

tour_time(matrix_time,collection_time,c(1,tours[[1]][3:(length(tours[[1]])-1)],dumpsite)) + tour_time(matrix_time,collection_time,tours[[2]]) +matrix_time[dumpsite,1] #20584.3

tour_time(matrix_time,collection_time,c(1,tours[[3]][2:length(tours[[3]])])) + tour_time(M,collection_time,tours[[4]]) + tour_time(M,collection_time,tours[[5]]) +  matrix_time[dumpsite,1] #23616.59

tour_time(matrix_time,collection_time,c(1,tours[[6]][2:length(tours[[6]])])) + tour_time(M,collection_time,tours[[7]]) + matrix_time[dumpsite,1] #17193.99

#vehicle 1
v1 <- list()
v1[[2]] <- tours[[1]][3:(length(tours[[1]])-1)]
v1[[1]] <- tours[[2]][2:(length(tours[[2]])-1)]


full_tour <- c(1,tours[[1]][3:(length(tours[[1]])-1)],tours[[2]],1)
tour_length(M, full_tour) #26.30561
plot_cvrp_tour(waste_nodes,v1, dumpsite, labels=FALSE, colors = rev(c("#1B9E77", "#D95F02")))+theme_void()
#[1] "#1B9E77" "#D95F02" "#7570B3" "#E7298A" "#66A61E" "#E6AB02" "#A6761D"

#vehicle 2
v2 <- list()
v2[[3]] <- c(tours[[3]][2:(length(tours[[3]])-1)])
v2[[2]] <- c(tours[[4]][2:(length(tours[[4]])-1)])
v2[[1]] <- c(tours[[5]][2:(length(tours[[5]])-1)])

full_tour <- c(1,tours[[3]][2:length(tours[[3]])],tours[[4]],tours[[5]],1)
tour_length(M, full_tour) #32.831

plot_cvrp_tour(waste_nodes,v2, dumpsite, labels=FALSE, colors=rev(c("#7570B3", "#E7298A", "#66A61E" )))+theme_void()

#vehicle 3
v3 <- list()

v3[[2]] <- c(tours[[6]][2:(length(tours[[6]])-1)])
v3[[1]] <- c(tours[[7]][2:(length(tours[[7]])-1)])

full_tour <- c(1,tours[[6]][2:length(tours[[6]])],tours[[7]],1)
tour_length(M, full_tour) #23.772

plot_cvrp_tour(waste_nodes,v3, dumpsite, labels=FALSE, colors = rev(c("#E6AB02", "#A6761D")))+theme_void()

```



k means case study 1
```{r}
system.time(sweep_solution <- sweep_depot_dumpsite (waste_nodes, 800, M, 1, 368))
plot_cvrp_tour(waste_nodes,sweep_solution, dumpsite = 368, labels=FALSE)

# solve TSP within each cluster

#cluster 1
st1 <- c(1,sweep_solution[[2]],368)
st1<- st1[order(st1)]

nn1<- nearest_neighbor_tour_start(M1,1) 
nn <- st1[nn1]
tour_length(M,nn) # 4020.028

gr1<- greedy_algorithm_tour(M1) 
gr <- st1[gr1]
tour_length(M,gr) #3012.169

ni1<- greedy_algorithm_tour(M1) 
ni <- st1[ni1]
tour_length(M,ni) #3012.169


system.time(i2opt <- improvement_2opt(M,nn, asymmetric = TRUE)) #no improvement
system.time(i3opt <- ThreeOpt_R_start(i2opt,M,max_improvements = 50)) #17.90794
tour_length(M,i3opt)
tour_length(M,i3opt) #3010.415
s1 <- reorder_tour(i3opt,1)

system.time(feasible_tour <- make_tour_feasible(M,st1))
tour_length(M,feasible_tour) # 21.41877

system.time(feasible_tour1_imp <- ThreeOpt_R_start(feasible_tour,M,max_improvements = 50))
feasible_tour1_imp <- reorder_tour(feasible_tour1_imp,1)
tour_length(M,feasible_tour1_imp) #16.44582


#cluster 2


st2 <- c(368,sweep_solution[[1]])
st2<- st2[order(st2)]


nn2<- nearest_neighbor_tour_start(M2,1) 
nn <- st2[nn2]
tour_length(M,nn) # 5021.154

gr2<- greedy_algorithm_tour(M2) 
gr <- st2[gr2]
tour_length(M,gr) #4016.888

ni2<- greedy_algorithm_tour(M2) 
ni <- st2[ni2]
tour_length(M,ni) #4016.888


system.time(i2opt <- improvement_2opt(M,ni, asymmetric = TRUE)) #no imp
system.time(i3opt <- ThreeOpt_R_start(i2opt,M,max_improvements = 50)) #17.90794

tour_length(M,i3opt) #3014.146
s2 <- reorder_tour(i3opt,368)


system.time(feasible_tour2 <- make_tour_feasible(M,st2))
tour_length(M,feasible_tour2)


system.time(feasible_tour2_imp <- ThreeOpt_R_start(feasible_tour2,M,max_improvements = 50))
 feasible_tour2_imp <- reorder_tour( feasible_tour2_imp,368)
tour_length(M,feasible_tour2_imp) #17.71427

###

s1 <- feasible_tour1_imp
s2 <- feasible_tour2_imp

solution <- list()
solution[[2]] <- s1[2:(length(s1)-2)]
solution[[1]] <- s2[2:(length(s2)-1)]

tour_length(M,s1) + tour_length(M,s2) + M[368,1]  # 35.35603

plot_cvrp_tour(waste_nodes,solution, dumpsite = 368, labels=FALSE)

plot_cvrp_tour(waste_nodes,solution, dumpsite = 368, labels=FALSE, nodes_to_avoid = c(1,368))

#### hacerlo feasible



```

CASE STUDY: PLOTS

```{r}

library(dplyr)
library(ggplot2) 

# all nodes
ggplot(data = waste_nodes, aes(x = x, y =y)) + geom_point() +
             geom_point(data = waste_nodes[c(367, 368),], aes(x = x, y =y), colour= "red", size=2) #+ 

# excluding depot and dump site
plot <- ggplot(data = waste_nodes[-c(1,368),], aes(x = x_coord, y =y_coord)) + geom_point()

#tour
 coordinates <- waste_nodes
 nn_3opt <- reorder(nn_3opt,1)
 tour <- nn_3opt[-c(1,368,369)]
 m <- coordinates[tour %>% as.numeric,]
 m <- data.frame(x = m$x[1:(nrow(m) -1)], 
                  y = m$y[1:(nrow(m) -1)],
                  xend = m$x[2:nrow(m)],
                  yend = m$y[2:nrow(m)])
 plot <- ggplot(data = waste_nodes[-c(1,368),], aes(x = x_coord, y =y_coord)) + geom_point() +
    geom_segment(data = m, aes(x = x, xend = xend, y = y, yend = yend)) 


# try nn

nn <- nearest_neighbor_tour_start(matrix_dist,1)
nn_2opt <- improvement_2opt(matrix_dist,nn)


```

```{r}

cvrp <- waste_nodes[-c(1,368),]
solution <- split_solution

 plot <- ggplot(data = cvrp, aes(x = x_coord, y =y_coord)) + geom_point() 
  
  for(i in 1:(length(solution)-1)){
    colors <- colorRampPalette(c("red","blue"))((length(solution)-1))
    
    
    if(i == 2) {subtour <- st1_3opt[2:209]} else {
      subtour <- c(solution[[i]])}
    #subtour <- solution[[i]]
    m <- waste_nodes[subtour %>% as.numeric,]
    m <- data.frame(x = m$x[1:(nrow(m) -1)], 
                    y = m$y[1:(nrow(m) -1)],
                    xend = m$x[2:nrow(m)],
                    yend = m$y[2:nrow(m)])
    plot <- plot + geom_segment(data = m, aes(x = x, xend = xend, y = y, yend = yend), color = colors[i]) 
   }
plot
```


