---
title: "R Notebook"
output: html_notebook
---

EXAMPLE INSTANCE: "A-n32-k5.txt"
31 CITIES, 1 DEPOT
5 VEHICLES

Optimal solution:


tour1 <- c(1, 22, 32, 20, 18, 14, 8, 27, 1)
tour2 <- c(1, 13, 2, 17, 31, 1)
tour3 <- c(1, 28, 25, 1)
tour4 <- c(1, 30, 19, 9, 10, 23, 16, 11, 26, 6, 21,1)
tour5 <- c(1, 15, 29, 12, 5, 24, 4, 3, 7,1)

Cost 787

```{r}
setwd("C:/Users/LiaDenisse/Documents/OR and DS/TSP")
n <- 32
capacity <- 100
vehicles <- 5
file_name <- "A-n32-k5.txt"
cvrp <- read.table(file = file_name, skip = 7, sep = "", col.names= c("node", "x_coord", "y_coord"), nrows= n)
cvrp_demand <- read.table(file = "A-n32-k5.txt", skip = 7+n+1 , sep = "", col.names= c("node", "demand"), nrows= n)
depot <- 1

distance_matrix <- function(x, y){
  M <- matrix(nrow = n, ncol = n)
  for(i in 1:length(x)){
    for(j in 1:length(y)){
      M[i,j]  <- sqrt((x[i] - x[j])^2 + (y[i] - y[j])^2)
    }
  }
  return(M)
}

M <- 
  distance_matrix(cvrp$x_coord, cvrp$y_coord)

```




Try the algorithms

```{r}
system.time(sweep_solution <- sweep(cvrp,100,M,depot=1)) #1273.48
solution <- list()
system.time(solution[[1]] <- improvement_2opt(M,c(1,sweep_solution[[1]],1))) # 0.04 
system.time(solution[[2]] <- improvement_2opt(M,c(1,sweep_solution[[2]],1))) #0.04
system.time(solution[[3]] <- improvement_2opt(M,c(1,sweep_solution[[3]],1))) #0
system.time(solution[[4]] <- improvement_2opt(M,c(1,sweep_solution[[4]],1))) #0.01

tour_length(M,solution[[1]]) +  tour_length(M,solution[[2]]) +tour_length(M,solution[[3]]) +tour_length(M,solution[[4]]) #791.9262

system.time(savings_solution <- savings(M, cvrp_demand, 100)) #843.6882

plot_cvrp_tour(cvrp,savings_solution) + theme_void()
plot_cvrp_tour(cvrp,solution) + theme_void()



```


Try Split
```{r}
# demand
demand <- cvrp_demand$demand

# get giant tour
nn <- nearest_neighbor_tour_start(M,1) #595.7104
nn_2opt <- improvement_2opt(M,nn) #494.598
nn_3opt <- ThreeOpt_R(nn_2opt,M) #472.4643
nn_3opt_2opt <- improvement_2opt(M,nn_3opt) #467.1055


system.time( gt <- greedy_algorithm_tour(M) )#585.8369
system.time (gt_2opt <- improvement_2opt(M,gt)) #472.4051
system.time( gt_3opt <- ThreeOpt_R(gt_2opt,M) )#467.1055


# split giant tour
giant_tour <-  gt_3opt #starts from the depot
giant_tour <- reorder_tour(giant_tour,1)
tour <- giant_tour[-length(giant_tour)]



system.time(split_solution <- split_R(tour,capacity,demand,M)) #816.8119

demand <- cvrp_demand$demand
plot_tour(cvrp,giant_tour) + theme_void()
plot_cvrp_tour(cvrp,split_solution) + theme_void()

solution <- list()
solution[[1]] <- improvement_2opt(M,c(1,split_solution[[1]],1))
solution[[2]] <- improvement_2opt(M,c(1,split_solution[[2]],1))
solution[[3]] <- improvement_2opt(M,c(1,split_solution[[3]],1))
solution[[4]] <- improvement_2opt(M,c(1,split_solution[[4]],1))
solution[[5]] <- improvement_2opt(M,c(1,split_solution[[5]],1))

plot_cvrp_tour(cvrp,solution) + theme_void()

tour_length(M,solution[[1]]) +  tour_length(M,solution[[2]]) +tour_length(M,solution[[3]]) +tour_length(M,solution[[4]]) +tour_length(M,solution[[5]]) #799.096


```

```{r}
	# optimal solution
tour <- c(1, 22, 32, 20, 18, 14, 8, 27, 13, 2, 17, 31, 28, 25, 30, 19, 9, 10, 23, 16, 11, 26, 6, 21, 15, 29, 12, 5, 24, 4, 3, 7)
split_solution <- split_R(tour,capacity,demand,M)
plot_cvrp_tour(cvrp,split_solution)

          
```