---
title: "R Notebook"
output: html_notebook



Package example instances
```{r}
setwd("C:/Users/LiaDenisse/Documents/OR and DS/TSP")
library(tspmeta)
tsp2 <- read_tsplib_instance("att532.tsp") # 532 cities
coords2 <- tsp2$coords
coords2 <- as.data.frame(coords2)
names(coords2) <- c("x_coord", "y_coord")
#tsp2 <- tsp2$dists
tsp1 <- read_tsplib_instance("dantzig42.tsp") #42 cities
coords1 <- tsp1$coords
coords1 <- as.data.frame(coords1)
names(coords1) <- c("x_coord", "y_coord")
tsp1 <- tsp1$dists
#system.time(tour2 <- run_solver(tsp2, method="2-opt"))
#Plot
#autoplot(r2, tour2)
```

distance function type att
```{r}

M <- matrix(,nrow=532, ncol=532)

for(i in 1:532){
  for(j in 1:532){
    M[i,j] <- distance_att(tsp2$coords, i,j)
  }
}

```



Comparing heuristics
```{r}

tsp <- M

system.time(rnn <- repetitive_nearest_neighbor_tour(tsp)) # dantzig42
system.time(nn <- nearest_neighbor_tour_start(tsp, 1))
system.time(gt <- greedy_algorithm_tour(tsp))
system.time(ni <- nearest_insertion_tour(tsp))


#tour length

tour_length(tsp, rnn)
tour_length(tsp, nn)
tour_length(tsp, gt)
tour_length(tsp, ni)

#2-opt improvement

system.time(rnn_2opt <- improvement_2opt(tsp,rnn))
system.time(nn_2opt <- improvement_2opt(tsp,nn))
system.time(gt_2opt <- improvement_2opt(tsp,gt))
system.time(ni_2opt <- improvement_2opt(tsp,ni))



system.time(rnn_2opt <- improvement_2opt_old(tsp,rnn, max_imp = 50))
system.time(nn_2opt <- improvement_2opt_old(tsp,nn, max_imp = 50))
system.time(gt_2opt <- improvement_2opt_old(tsp,gt, max_imp = 50))
system.time(ni_2opt <- improvement_2opt_old(tsp,ni, max_imp = 50))


#3-opt improvement

system.time(rnn_3opt <- ThreeOpt_R_greedy(rnn_2opt,tsp, max_improvements = 10))
system.time(nn_3opt <- ThreeOpt_R_greedy(nn_2opt,tsp, max_improvements = 10))
system.time(gt_3opt <- ThreeOpt_R_greedy(gt_2opt,tsp, max_improvements = 10))
system.time(ni_3opt <- ThreeOpt_R_greedy(ni_2opt,tsp, max_improvements = 10))

tour_length(tsp,rnn_3opt)
tour_length(tsp,nn_3opt)
tour_length(tsp,gt_3opt)
tour_length(tsp,ni_3opt)

#Plots

plot_tour(coords1, rnn_3opt, "Tour found with rnn algorithm, 2-opt and 3-opt improvement")
plot_tour(coords1, nn_3opt, "Tour found with nearest neighbor algorithm, 2-opt and 3-opt improvement")
plot_tour(coords1, ni_3opt, "Tour found with nearest insertion algorithm, 2-opt and 3-opt improvement")
plot_tour(coords1, gt_3opt, labels= FALSE) + theme_void()

```
