---
title: "R Notebook"
output: html_notebook
---

Load  data
```{r}
setwd("C:/Users/LiaDenisse/Documents/OR and DS/TSP")
#library(Rcpp)

#file_name <- "ftv44.atsp.txt"  # greedy 2262 -> 2181 || nn: 2450 --> 2177 || opt: 1613
#file_name <- "p43.atsp.txt"    # greedy 5819 -> 5639 ||nearest neighbor: 5768 -> 5642 || opt: 5620
file_name <- "rbg443.atsp.txt"  # greedy 2755 -> no improvement || nearest neighbor 3922 -> 3880 || opt: 2720
n <- 443

atsp <- scan(file = file_name, what = double(), nmax = n*n, sep = "", skip = 7)
atsp <- matrix(atsp, ncol = n, byrow = TRUE)

```

Greedy Algorithm

```{r}

#### Auxiliary functions ####

#return position (i,j) of minimum element in a matrix
min_matrix <- function(M){
  return (arrayInd(which.min(M),dim(M)))
}

#return position (i,j) of maximum element in a matrix
max_matrix <- function(M){
  return (arrayInd(which.max(M),dim(M)))
}

# change vector (i,j) to (j,i)
flip_pair <- function(pair){
  new_pair <- matrix(nrow=1,ncol=2)
  new_pair[1] <- pair[2]
  new_pair[2] <- pair[1]
  return(new_pair)
}

# retrieve the sequence from matrix representation starting from "start"  
nodes_in_sequence <-function(matrix, start){
  s <- c(start)
  #retrieve the sequence
  if (max(matrix[start,],na.rm=T)== -Inf) { return (1)} else {
  while (max(matrix[tail(s,n=1),],na.rm=T) != 0 ){
    s <- c(s,which.max(matrix[tail(s,n=1),]))
    if (length(s) > 1 & tail(s,n=1) == start) { break } # end because we have a cycle
    if(max(matrix[tail(s,n=1),],na.rm=T) == -Inf) { break } #end because the node is not connected to any other node
  }
  return(s)
  }
} 

#is the sequence a cycle  ?
is_cycle <-function(matrix, start){
   s <- nodes_in_sequence(matrix,start)
   return(tail(s,n=1) == start)
} 

#### greedy algorithm ####

#atsp is an asymmetric distance matrix
greedy_algorithm_tour <- function(atsp) {
  
    n <- dim(atsp)[1]
    X <- matrix(nrow=n, ncol=n) #tour representation in a matrix, it will be initialized with NA
    C<- atsp  # distances matrix
    iteration <- 0
    
    for (i in 1:n){
      C[i,i] <- Inf
    }
     start_node <- min_matrix(C)[1] 
     
    while (sum(is.na(X)) > 0){
      
      # find the minimum element in C
      min <- min_matrix(C) # min = (i,j)
      
      # temporary connect i to j
      X[min] <- 1
      
       #check that no cycles occur until we have connected all nodes
     
      oldw <- getOption("warn")
      options(warn = -1)
      if (is_cycle(X,min[1]) & length(nodes_in_sequence(X,min[1])) != n+1) {
      options(warn = oldw)  
         X[min] <- 0
         C[min] <- Inf
      } else {
        
        # update X and C matrices accordingly
        
        X[min] <- 1            #X[i,j] = 1
        C[min] <- Inf
        X[flip_pair(min)] <- 0 #X[j,i] = 0
        C[flip_pair(min)] <- Inf
        
        for(i in 1:n) {
          if(i != min[1]) {  X[i,min[2]] <- 0 
                             C[i,min[2]] <- Inf  }
          if(i != min[2]) {  X[min[1],i] <- 0
                             C[min[1],i] <- Inf}
        }
      }
      iteration <- iteration + 1
    }
     
    #retrieve tour
    return(nodes_in_sequence(X,start_node))
}

```



Greedy Algorithm 2

```{r}

#### greedy algorithm 2 ####

#waste_edges is an asymmetric distance matrix

greedy_algorithm_tour <- function(edges) {
  
    n <- max(edges$from)
    X <- matrix(nrow=n, ncol=n) #tour representation in a matrix, it will be initialized with NA
    
    edge_from <- edges[edges$distance == min(edges[edges$type == 2,]$distance),]$from
    edge_to <- edges[edges$distance == min(edges[edges$type == 2,]$distance),]$to
    
    C<- atsp  # distances matrix
    iteration <- 0
    
    for (i in 1:n){
      C[i,i] <- Inf
    }
     start_node <- min_matrix(C)[1] 
     
    while (sum(is.na(X)) > 0){
      
      # find the minimum element in C
      min <- min_matrix(C) # min = (i,j)
      
      # temporary connect i to j
      X[min] <- 1
      
       #check that no cycles occur until we have connected all nodes
     
      oldw <- getOption("warn")
      options(warn = -1)
      if (is_cycle(X,min[1]) & length(nodes_in_sequence(X,min[1])) != n+1) {
      options(warn = oldw)  
         X[min] <- 0
         C[min] <- Inf
      } else {
        
        # update X and C matrices accordingly
        
        X[min] <- 1            #X[i,j] = 1
        C[min] <- Inf
        X[flip_pair(min)] <- 0 #X[j,i] = 0
        C[flip_pair(min)] <- Inf
        
        for(i in 1:n) {
          if(i != min[1]) {  X[i,min[2]] <- 0 
                             C[i,min[2]] <- Inf  }
          if(i != min[2]) {  X[min[1],i] <- 0
                             C[min[1],i] <- Inf}
        }
      }
      iteration <- iteration + 1
    }
     
    #retrieve tour
    return(nodes_in_sequence(X,start_node))
}

```



2-Opt

```{r}
##### Auxiliary functions ##########################################

# matrix_tour C++ function: Transforms a tour from its sequence representation to its matrix representation
 

# TwoOptSwap C++ function: swaps edges (i, i+1) and (k, k+1) in a given tour, where i<k

#return position (i,j) of maximum element in a matrix
max_matrix <- function(M){
  return (arrayInd(which.max(M),dim(M)))
}

# Node after node1
next_node <- function(tour, node1){
  return(tour[(which(tour==node1)[1]+1)])
}

# Node before node1
previous_node <- function(tour, node1){
  if (length(which(tour==node1))== 1) {
  return(tour[(which(tour==node1)[1]-1)])} else {
    return(tour[(which(tour==node1)[2]-1)])
  }
}

# neighborhood of an edge, if edge is (N(i),N(i+1)), neighborhood is (N(i-1),N(i),N(i+1),N(i+2))
# i index, N(i) element in the position i of the tour

neighborhood <- function(tour, edge){
  n<- length(tour)
  pos1 <- which(tour==edge[1])
    pos2 <- which(tour==edge[2])
    if ( length(pos1) == 2) {
      pos1_1  <- pos1[1]
      pos1_2 <- pos1[2]} else {
      pos1_1 <- pos1
      pos1_2 <- 2*n}
    if ( length(pos2) == 2) {
       pos2_1  <- pos2[1]
       pos2_2 <- pos2[2]} else {
      pos2_1 <- pos2
      pos2_2 <- 2*n}
    
    previous_node_pos <- which(tour == previous_node(tour,edge[1]))[1]
    next_node_pos <- which(tour== next_node(tour,edge[2]))[1]
    return(c(pos1_1, pos1_2, pos2_1, pos2_2, previous_node_pos, next_node_pos))
}


#####  2-opt algorithm #####

#it starts with a given tour

improvement_2opt_A <- function(tsp, current_tour) {
  
  n <- length(current_tour)-1
  C<- tsp  # distances matrix
  starting_min_distance <- tour_length(C, current_tour)
  min_distance <- starting_min_distance 
  X <- matrix_tour(current_tour) #matrix representation of the tour
  CX <- C*X #distances of the edges of the current tour
  
  #Vector F and B: cumulative sum of distances when walking the tour forward and backward
   #initialize F and V vector
  f <- cumsumF(C,current_tour)
  b <- cumsumB(C,current_tour)
  
  it <- 0
  
  improvements <- 0
  unsucessfull_search <- 0
  
  continue <- TRUE #boolean flag
  
  while(continue){
    
    #start with the largest edge in the current tour
    edge1 <- max_matrix(CX) 
    CX[edge1]<- 0
    it2 <- 0
    neighborhood_edge1 <- neighborhood(current_tour,edge1)
    
   #search for a better tour
    new_tour <- TwoOpt_New_Tour_A(neighborhood_edge1, current_tour, C, min_distance, f, b)
    
    #improvement?
    if (length(new_tour) == n+2){  #new_tour[n+2] is the gain, if there's any
      current_tour <- new_tour[1:(n+1)]
      min_distance <- min_distance - new_tour[n+2]
      X <- matrix_tour(current_tour)
      CX <- C*X 
      f <- cumsumF(C,current_tour)
      b <- cumsumB(C,current_tour) 
      
      improvements <- improvements + 1
      #cat("unsucessful searches: ", unsucessfull_search, "\n")
      cat("Number of improvements: ", improvements, "\n")
      cat("Tour distance: ",min_distance, "\n" )
      #unsucessfull_search <- 0
    } else {
      #cat("unsucessful searches: ", unsucessfull_search, "\n")
      unsucessfull_search <- unsucessfull_search + 1
    }
    
    #stopping criterion, when distance is improved in at least 30%
      if (abs(min_distance-starting_min_distance)/starting_min_distance > .3 | sum(CX)== 0 ) {
         cat("unsucessfull search: ",unsucessfull_search , "\n")
         continue = FALSE }
  
  }
    return(current_tour)
}



#####  otra version #####
improvement_2opt_A_v2 <- function(tsp, current_tour) {
  
  n <- length(current_tour)-1
  C<- tsp  # distances matrix
  starting_min_distance <- tour_length(C, current_tour)
  min_distance <- starting_min_distance 
  #X <- matrix_tour(current_tour) #matrix representation of the tour
  #CX <- C*X #distances of the edges of the current tour
  #Vector F and B: cumulative sum of distances when walking the tour forward and backward
   #initialize F and V vector
  f <- cumsumF(C,current_tour)
  b <- cumsumB(C,current_tour)
  
  it <- 0
  e<- 1
  improvements <- 0
  unsucessfull_search <- 0
  
  continue <- TRUE #boolean flag
  
  while(continue){
    
    #start with the first edge in the current tour if distance > 0
    
  
      edge1 <- c(current_tour[e], current_tour[e+1])
    
    neighborhood_edge1 <- neighborhood(current_tour,edge1)
  
    #search for a better tour
    new_tour <- TwoOpt_New_Tour_A(neighborhood_edge1, current_tour, C, min_distance, f, b)
    
    #improvement?
    if (length(new_tour) == n+2){  #new_tour[n+2] is the gain, if there's any
      current_tour <- new_tour[1:(n+1)]
      min_distance <- min_distance - new_tour[n+2]
      e <- 1
      #X <- matrix_tour(current_tour)
      #CX <- C*X 
      f <- cumsumF(C,current_tour)
      b <- cumsumB(C,current_tour) 
      improvements <- improvements + 1
      cat("unsucessful searches: ", unsucessfull_search, "\n")
      cat("Number of improvements: ", improvements, "\n")
      cat("Tour distance: ",min_distance, "\n" )
      #unsucessfull_search <- 0
    } else {
      e <- e+1
      cat("unsucessful searches: ", unsucessfull_search, "\n")
      unsucessfull_search <- unsucessfull_search + 1
    }
    
    #stopping criterion, when distance is improved in at least 30%
      if (abs(min_distance-starting_min_distance)/starting_min_distance > .3 |  e == n ) {
         cat("unsucessfull search: ",unsucessfull_search , "\n")
         continue = FALSE }
  
  }
    return(current_tour)
}



```


Try algorithms

```{r}
gt <- greedy_algorithm_tour(atsp)
nn <- nearest_neighbor_tour_start(atsp, 1)

tour_length(atsp,gt) 

imp2 <- improvement_2opt_A(atsp,nn)   



```